### ISSUE TITLE
Error in custom modal example with RC.6

### ISSUE THREAD

**Issue by hpop** [shlomiassaf/angular2-modal#183]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
At startup following error is thrown:
```
Error: Component CustomModal is not part of any NgModule or the module has not been imported into your module.
```
The same is happening in my current project.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Just change the Version in the example for CustomModal to RC.6
http://plnkr.co/edit/LAVfwp67nVH4tx3tnFJI?p=preview

* **What is the expected behavior?**
Normal application startup.

* **Please tell us about your environment:**
- Angular version: 2.0.0-RC.6
- Browser: [all]

**Comment by hpop** [comment]
Adding `CustomModal` to the declaration array actually helps.

**Comment by shlomiassaf** [comment]
Fixed in plunker.

**Comment by andfs** [comment]
This error still ocurr in the final angular release 2.0.0
I put the ModalModule.forRoot() and get the error. If I declare my modal, angular doesn´t find him.

**Comment by ravtakhar** [comment]
Using 2.4 and this is still occurring for me as well.

**Comment by AsmaGargouri** [comment]
@hpop , this works thanks
